cacheFolder: ./.yarn/cache

compressionLevel: mixed

enableGlobalCache: false

nmSelfReferences: false

nodeLinker: node-modules

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"

yarnPath: .yarn/releases/yarn-4.1.0.cjs
