nmSelfReferences: false

nodeLinker: node-modules

yarnPath: '.yarn/releases/yarn-4.1.0.cjs'
cacheFolder: './.yarn/cache'

packageExtensions:
  debug@*:
    dependencies:
      supports-color: '*'
# plugins:
#   - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
#     spec: "@yarnpkg/plugin-typescript"
