nmSelfReferences: false

nodeLinker: node-modules

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
# plugins:
#   - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
#     spec: "@yarnpkg/plugin-typescript"
